const dummyProducts = [
  {
    id: 1,
    title: 'Soothing Cleanser',
    slug: 'product-1',
    categories: ['skincare', 'facewash', 'facepack'],
    price: 12,
    sale_price: 10,
    sale_percent: 10,
    rating: 5,
    imageUrl: 'product-1.png',
    imageWidth: 640,
    imageHeight: 640,
  },
  {
    id: 2,
    title: 'Gentle Skin Cleanser',
    slug: 'product-1',
    categories: ['skincare', 'facewash', 'facepack'],
    price: 30,
    sale_price: 25,
    sale_percent: 20,
    rating: 4,
    imageUrl: 'product-2.png',
    imageWidth: 640,
    imageHeight: 640,
  },
  {
    id: 3,
    title: 'Moisturizing Lotion',
    slug: 'product-1',
    categories: ['skincare', 'facewash', 'facepack'],
    price: 30,
    rating: 5,
    imageUrl: 'product-3.png',
    imageWidth: 640,
    imageHeight: 640,
  },
  {
    id: 4,
    title: 'Micro-Sculpting Cream',
    slug: 'product-1',
    categories: ['skincare', 'facewash', 'facepack'],
    price: 12,
    sale_price: 10,
    sale_percent: 25,
    rating: 5,
    imageUrl: 'product-5.png',
    imageWidth: 640,
    imageHeight: 640,
  },
  {
    id: 5,
    title: 'Night Infusion Cream',
    slug: 'product-1',
    categories: ['skincare', 'facewash', 'facepack'],
    price: 20,
    sale_price: 30,
    sale_percent: 30,
    rating: 5,
    imageUrl: 'product-6.png',
    imageWidth: 640,
    imageHeight: 640,
  },
  {
    id: 6,
    title: 'Night Moisturizer',
    slug: 'product-1',
    categories: ['skincare', 'facewash', 'facepack'],
    price: 30,
    sale_price: 50,
    sale_percent: 20,
    rating: 5,
    imageUrl: 'product-7.png',
    imageWidth: 640,
    imageHeight: 640,
  },
  {
    id: 7,
    title: 'Restorative Cream',
    slug: 'product-1',
    categories: ['skincare', 'facewash', 'facepack'],
    price: 100,
    sale_price: 89,
    sale_percent: 20,
    rating: 5,
    imageUrl: 'product-8.png',
    imageWidth: 640,
    imageHeight: 640,
  },
  {
    id: 8,
    title: 'Renewal B3 Serum',
    slug: 'product-1',
    categories: ['skincare', 'facewash', 'facepack'],
    price: 30,
    sale_price: 25,
    sale_percent: 10,
    rating: 1,
    imageUrl: 'product-9.png',
    imageWidth: 640,
    imageHeight: 640,
  },
  {
    id: 9,
    title: 'Intense Advanced Serum',
    slug: 'product-1',
    categories: ['skincare', 'facewash', 'facepack'],
    price: 40,
    sale_price: 30,
    sale_percent: 30,
    rating: 2.4,
    imageUrl: 'product-10.png',
    imageWidth: 640,
    imageHeight: 640,
  },
  {
    id: 10,
    title: 'Repair Concentrate Serum',
    slug: 'product-1',
    categories: ['skincare', 'facewash', 'facepack'],
    price: 75,
    sale_price: 50,
    sale_percent: 40,
    rating: 2.4,
    imageUrl: 'product-11.png',
    imageWidth: 640,
    imageHeight: 640,
  },
];

export const featuredCategories = [
  {
    id: 1,
    url: 'skin-care',
    backgroundColor: 'bg-theme_green-300',
    title: 'Skin Care',
    details: 'Glowing skin every minutes & seconds',
    imgUrl: 'product-6.png',
    width: 338,
    height: 308,
  },
  {
    id: 2,
    url: 'skin-care',
    backgroundColor: 'bg-yellow-200',
    title: 'Face Mask',
    details: 'A classic hydration treatment',
    imgUrl: 'product-14.png',
    width: 350,
    height: 350,
  },
  {
    id: 3,
    url: 'skin-care',
    backgroundColor: 'bg-pink-200',
    title: 'Natural Oil',
    details: 'Protect against environmental irritants',
    imgUrl: 'product-5.png',
    width: 350,
    height: 350,
  },
];

export default dummyProducts;
