const dummyProducts = [
  {
    id: 1,
    title: 'Soothing Cleanser',
    slug: 'product-1',
    categories: ['skincare', 'facewash', 'facepack'],
    price: 12,
    sale_price: 10,
    sale_percent: 10,
    rating: 5,
    imageUrl: 'product-1.png',
    imageWidth: 640,
    imageHeight: 640,
  },
  {
    id: 2,
    title: 'Gentle Skin Cleanser',
    slug: 'product-1',
    categories: ['skincare', 'facewash', 'facepack'],
    price: 30,
    sale_price: 25,
    sale_percent: 10,
    rating: 4,
    imageUrl: 'product-2.png',
    imageWidth: 640,
    imageHeight: 640,
  },
  {
    id: 3,
    title: 'Moisturizing Lotion',
    slug: 'product-1',
    categories: ['skincare', 'facewash', 'facepack'],
    price: 30,
    rating: 5,
    imageUrl: 'product-3.png',
    imageWidth: 640,
    imageHeight: 640,
  },
  {
    id: 4,
    title: 'Micro-Sculpting Cream',
    slug: 'product-1',
    categories: ['skincare', 'facewash', 'facepack'],
    price: 12,
    sale_price: 10,
    sale_percent: 10,
    rating: 5,
    imageUrl: 'product-5.png',
    imageWidth: 640,
    imageHeight: 640,
  },
  {
    id: 5,
    title: 'Night Infusion Cream',
    slug: 'product-1',
    categories: ['skincare', 'facewash', 'facepack'],
    price: 12,
    sale_price: 10,
    sale_percent: 10,
    rating: 5,
    imageUrl: 'product-6.png',
    imageWidth: 640,
    imageHeight: 640,
  },
  {
    id: 6,
    title: 'Night Moisturizer',
    slug: 'product-1',
    categories: ['skincare', 'facewash', 'facepack'],
    price: 12,
    sale_price: 10,
    sale_percent: 10,
    rating: 5,
    imageUrl: 'product-7.png',
    imageWidth: 640,
    imageHeight: 640,
  },
  {
    id: 7,
    title: 'Restorative Cream',
    slug: 'product-1',
    categories: ['skincare', 'facewash', 'facepack'],
    price: 12,
    sale_price: 10,
    sale_percent: 10,
    rating: 5,
    imageUrl: 'product-8.png',
    imageWidth: 640,
    imageHeight: 640,
  },
  {
    id: 8,
    title: 'Renewal B3 Serum',
    slug: 'product-1',
    categories: ['skincare', 'facewash', 'facepack'],
    price: 30,
    sale_price: 25,
    sale_percent: 10,
    rating: 1,
    imageUrl: 'product-9.png',
    imageWidth: 640,
    imageHeight: 640,
  },
  {
    id: 9,
    title: 'Intense Advanced Serum',
    slug: 'product-1',
    categories: ['skincare', 'facewash', 'facepack'],
    price: 12,
    sale_price: 10,
    sale_percent: 10,
    rating: 2.4,
    imageUrl: 'product-10.png',
    imageWidth: 640,
    imageHeight: 640,
  },
  {
    id: 10,
    title: 'Repair Concentrate Serum',
    slug: 'product-1',
    categories: ['skincare', 'facewash', 'facepack'],
    price: 12,
    sale_price: 10,
    sale_percent: 10,
    rating: 2.4,
    imageUrl: 'product-11.png',
    imageWidth: 640,
    imageHeight: 640,
  },
];

export default dummyProducts;
