export const attributes = [
  {
    id: 1,
    title: 'Size',
    slug: 'pa_size',
    terms: [
      { id: 1, title: 'S' },
      { id: 2, title: 'M' },
      { id: 3, title: 'L' },
      { id: 4, title: 'XL' },
    ],
  },
  {
    id: 2,
    title: 'Weight',
    slug: 'pa_weight',
    terms: [
      { id: 1, title: '10gm' },
      { id: 2, title: '15gm' },
      { id: 3, title: '30gm' },
      { id: 4, title: '50gm' },
    ],
  },
];

export const dummyProducts = [
  {
    id: 1,
    title: 'Soothing Cleanser',
    slug: 'product-1',
    categories: ['skincare', 'facewash', 'facepack'],
    price: 12,
    sale_price: 10,
    sale_percent: 10,
    rating: 5,
    stock: 40,
    imageUrl: 'product-1.png',
    gallery: [
      { id: 1, url: 'product-1.png' },
      { id: 2, url: 'product-2.png' },
      { id: 3, url: 'product-3.png' },
      { id: 4, url: 'product-6.png' },
      { id: 5, url: 'product-5.png' },
    ],
    imageWidth: 640,
    imageHeight: 640,
    type: 2, // 1 = Simple Product, 2 = Variable Product
    variations: [
      {
        id: '1_v1',
        price: 20,
        sale_price: 15,
        stock: 20,
        attributes: ['S', '10gm'],
        bgColor: 'bg-yellow-200',
      },
      {
        id: '1_v2',
        price: 25,
        sale_price: 20,
        stock: 25,
        attributes: ['M', '15gm'],
        bgColor: 'bg-pink-200',
      },
      {
        id: '1_v3',
        price: 30,
        sale_price: 25,
        stock: 16,
        attributes: ['L', '30gm'],
        bgColor: 'bg-purple-200',
      },
      {
        id: '1_v4',
        price: 40,
        sale_price: 30,
        stock: 10,
        attributes: ['XL', '50gm'],
        bgColor: 'bg-theme_green-300',
      },
    ],
  },
  {
    id: 2,
    title: 'Gentle Skin Cleanser',
    slug: 'product-2',
    categories: ['skincare', 'facewash', 'facepack'],
    price: 30,
    sale_price: 25,
    sale_percent: 20,
    rating: 4,
    stock: 44,
    imageUrl: 'product-2.png',
    gallery: [
      { id: 1, url: 'product-2.png' },
      { id: 2, url: 'product-6.png' },
      { id: 3, url: 'product-3.png' },
      { id: 4, url: 'product-6.png' },
      { id: 5, url: 'product-5.png' },
    ],
    imageWidth: 640,
    imageHeight: 640,
    type: 2, // 1 = Simple Product, 2 = Variable Product
    variations: [
      {
        id: '2_v1',
        price: 14,
        sale_price: 10,
        stock: 20,
        attributes: ['Small', 'Red'],
        bgColor: 'bg-pink-200',
      },
      {
        id: '2_v2',
        price: 18,
        sale_price: 15,
        stock: 20,
        attributes: ['Medium', 'Black'],
        bgColor: 'bg-yellow-200',
      },
      {
        id: '2_v3',
        price: 27,
        sale_price: 20,
        stock: 16,
        attributes: ['Large', 'White'],
        bgColor: 'bg-purple-200',
      },
    ],
  },
  {
    id: 3,
    title: 'Moisturizing Lotion',
    slug: 'product-3',
    categories: ['skincare', 'facewash', 'facepack'],
    price: 30,
    rating: 5,
    type: 1, // 1 = Simple Product, 2 = Variable Product
    stock: 50,
    imageUrl: 'product-3.png',
    gallery: [
      { id: 1, url: 'product-3.png' },
      { id: 2, url: 'product-2.png' },
      { id: 3, url: 'product-7.png' },
      { id: 4, url: 'product-6.png' },
      { id: 5, url: 'product-5.png' },
    ],
    imageWidth: 640,
    imageHeight: 640,
  },
  {
    id: 4,
    title: 'Micro-Sculpting Cream',
    slug: 'product-4',
    categories: ['skincare', 'facewash', 'facepack'],
    price: 18,
    sale_price: 15,
    sale_percent: 25,
    rating: 5,
    type: 1, // 1 = Simple Product, 2 = Variable Product
    stock: 10,
    imageUrl: 'product-5.png',
    gallery: [
      { id: 1, url: 'product-5.png' },
      { id: 2, url: 'product-2.png' },
      { id: 3, url: 'product-3.png' },
      { id: 4, url: 'product-6.png' },
      { id: 5, url: 'product-9.png' },
    ],
    imageWidth: 640,
    imageHeight: 640,
  },
  {
    id: 5,
    title: 'Night Infusion Cream',
    slug: 'product-5',
    categories: ['skincare', 'facewash', 'facepack'],
    price: 40,
    sale_price: 30,
    sale_percent: 30,
    rating: 5,
    type: 1, // 1 = Simple Product, 2 = Variable Product
    stock: 20,
    imageUrl: 'product-6.png',
    gallery: [
      { id: 1, url: 'product-6.png' },
      { id: 2, url: 'product-2.png' },
      { id: 3, url: 'product-3.png' },
      { id: 4, url: 'product-6.png' },
      { id: 5, url: 'product-10.png' },
    ],
    imageWidth: 640,
    imageHeight: 640,
  },
  {
    id: 6,
    title: 'Night Moisturizer',
    slug: 'product-6',
    categories: ['skincare', 'facewash', 'facepack'],
    price: 90,
    sale_price: 50,
    sale_percent: 20,
    rating: 5,
    type: 1, // 1 = Simple Product, 2 = Variable Product
    stock: 10,
    imageUrl: 'product-7.png',
    gallery: [
      { id: 1, url: 'product-7.png' },
      { id: 2, url: 'product-2.png' },
      { id: 3, url: 'product-3.png' },
      { id: 4, url: 'product-6.png' },
      { id: 5, url: 'product-5.png' },
    ],
    imageWidth: 640,
    imageHeight: 640,
  },
  {
    id: 7,
    title: 'Restorative Cream',
    slug: 'product-7',
    categories: ['skincare', 'facewash', 'facepack'],
    price: 100,
    sale_price: 70,
    sale_percent: 20,
    rating: 5,
    type: 1, // 1 = Simple Product, 2 = Variable Product
    stock: 5,
    imageUrl: 'product-8.png',
    gallery: [
      { id: 1, url: 'product-8.png' },
      { id: 2, url: 'product-2.png' },
      { id: 3, url: 'product-3.png' },
      { id: 4, url: 'product-6.png' },
      { id: 5, url: 'product-5.png' },
    ],
    imageWidth: 640,
    imageHeight: 640,
  },
  {
    id: 8,
    title: 'Renewal B3 Serum',
    slug: 'product-8',
    categories: ['skincare', 'facewash', 'facepack'],
    price: 30,
    sale_price: 25,
    sale_percent: 10,
    rating: 1,
    type: 1, // 1 = Simple Product, 2 = Variable Product
    stock: 30,
    imageUrl: 'product-9.png',
    gallery: [
      { id: 1, url: 'product-9.png' },
      { id: 2, url: 'product-2.png' },
      { id: 3, url: 'product-3.png' },
      { id: 4, url: 'product-6.png' },
      { id: 5, url: 'product-5.png' },
    ],
    imageWidth: 640,
    imageHeight: 640,
  },
  {
    id: 9,
    title: 'Intense Advanced Serum',
    slug: 'product-9',
    categories: ['skincare', 'facewash', 'facepack'],
    price: 40,
    sale_price: 30,
    sale_percent: 30,
    rating: 4,
    type: 1, // 1 = Simple Product, 2 = Variable Product
    stock: 15,
    imageUrl: 'product-10.png',
    gallery: [
      { id: 1, url: 'product-10.png' },
      { id: 2, url: 'product-2.png' },
      { id: 3, url: 'product-3.png' },
      { id: 4, url: 'product-6.png' },
      { id: 5, url: 'product-5.png' },
    ],
    imageWidth: 640,
    imageHeight: 640,
  },
  {
    id: 10,
    title: 'Repair Concentrate Serum',
    slug: 'product-10',
    categories: ['skincare', 'facewash', 'facepack'],
    price: 75,
    sale_price: 50,
    sale_percent: 40,
    rating: 4,
    type: 1, // 1 = Simple Product, 2 = Variable Product
    stock: 70,
    imageUrl: 'product-11.png',
    gallery: [
      { id: 1, url: 'product-11.png' },
      { id: 2, url: 'product-2.png' },
      { id: 3, url: 'product-3.png' },
      { id: 4, url: 'product-6.png' },
      { id: 5, url: 'product-5.png' },
    ],
    imageWidth: 640,
    imageHeight: 640,
  },
  {
    id: 11,
    title: 'Repair Concentrate Serum',
    slug: 'product-11',
    categories: ['skincare', 'facewash', 'facepack'],
    price: 30,
    sale_price: 20,
    sale_percent: 40,
    rating: 5,
    type: 1, // 1 = Simple Product, 2 = Variable Product
    stock: 40,
    imageUrl: 'product-12.png',
    gallery: [
      { id: 1, url: 'product-12.png' },
      { id: 2, url: 'product-2.png' },
      { id: 3, url: 'product-3.png' },
      { id: 4, url: 'product-6.png' },
      { id: 5, url: 'product-5.png' },
    ],
    imageWidth: 640,
    imageHeight: 640,
  },
  {
    id: 12,
    title: 'Repair Concentrate Serum',
    slug: 'product-12',
    categories: ['skincare', 'facewash', 'facepack'],
    price: 75,
    sale_price: 55,
    sale_percent: 40,
    rating: 5,
    type: 1, // 1 = Simple Product, 2 = Variable Product
    stock: 60,
    imageUrl: 'product-13.png',
    gallery: [
      { id: 1, url: 'product-13.png' },
      { id: 2, url: 'product-2.png' },
      { id: 3, url: 'product-3.png' },
      { id: 4, url: 'product-6.png' },
      { id: 5, url: 'product-5.png' },
    ],
    imageWidth: 640,
    imageHeight: 640,
  },
  {
    id: 13,
    title: 'Repair Concentrate Serum',
    slug: 'product-13',
    categories: ['skincare', 'facewash', 'facepack'],
    price: 95,
    sale_price: 70,
    sale_percent: 40,
    rating: 5,
    type: 1, // 1 = Simple Product, 2 = Variable Product
    stock: 20,
    imageUrl: 'product-14.png',
    gallery: [
      { id: 1, url: 'product-14.png' },
      { id: 2, url: 'product-2.png' },
      { id: 3, url: 'product-3.png' },
      { id: 4, url: 'product-6.png' },
      { id: 5, url: 'product-5.png' },
    ],
    imageWidth: 640,
    imageHeight: 640,
  },
  {
    id: 14,
    title: 'Repair Concentrate Serum',
    slug: 'product-14',
    categories: ['skincare', 'facewash', 'facepack'],
    price: 140,
    sale_price: 100,
    sale_percent: 40,
    rating: 3,
    type: 1, // 1 = Simple Product, 2 = Variable Product
    stock: 40,
    imageUrl: 'product-15.png',
    gallery: [
      { id: 1, url: 'product-15.png' },
      { id: 2, url: 'product-2.png' },
      { id: 3, url: 'product-3.png' },
      { id: 4, url: 'product-6.png' },
      { id: 5, url: 'product-5.png' },
    ],
    imageWidth: 640,
    imageHeight: 640,
  },
];

export const getProducts = () => dummyProducts;

export const getProductById = (id) => {
  const product = dummyProducts.filter((item) => item.id === id);
  return product[0] || null;
};

export const getProductBySlug = (slug) => {
  const product = dummyProducts.filter((item) => item.slug === slug);
  return product[0] || null;
};

export const focusClasses =
  'focus:outline-none focus-visible:ring-2 focus-visible:ring-theme_green focus-visible:ring-opacity-75';
