const dummyProducts = [
  {
    id: 1,
    title: 'Soothing Cleanser',
    slug: 'product-1',
    categories: ['skincare', 'facewash', 'facepack'],
    price: 12,
    sale_price: 10,
    sale_percent: 10,
    rating: 5,
    imageUrl: 'product-1.png',
  },
  {
    id: 2,
    title: 'Gentle Skin Cleanser',
    slug: 'product-1',
    categories: ['skincare', 'facewash', 'facepack'],
    price: 30,
    sale_price: 25,
    sale_percent: 10,
    rating: 5,
    imageUrl: 'product-2.png',
  },
  {
    id: 3,
    title: 'Soothing Cleanser',
    slug: 'product-1',
    categories: ['skincare', 'facewash', 'facepack'],
    price: 12,
    sale_price: 10,
    sale_percent: 10,
    rating: 5,
    imageUrl: 'product-1.png',
  },
  {
    id: 4,
    title: 'Soothing Cleanser',
    slug: 'product-1',
    categories: ['skincare', 'facewash', 'facepack'],
    price: 12,
    sale_price: 10,
    sale_percent: 10,
    rating: 5,
    imageUrl: 'product-1.png',
  },
  {
    id: 5,
    title: 'Soothing Cleanser',
    slug: 'product-1',
    categories: ['skincare', 'facewash', 'facepack'],
    price: 12,
    sale_price: 10,
    sale_percent: 10,
    rating: 5,
    imageUrl: 'product-1.png',
  },
];

export default dummyProducts;
