import { AnimateSharedLayout } from 'framer-motion';
import NextNprogress from 'nextjs-progressbar';
import Head from 'next/head';
import { ViewportProvider } from '../src/context/ViewPortContext';
import { FixedHeaderProvider } from '../src/context/FixedHeaderContext';
import { CartProvider } from '../src/context/CartContext';
import Layout from '../src/components/widgets/Layout';

import '../src/assets/scss/globals.scss';

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Next Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <NextNprogress color="#1CE2D8" startPosition={0.3} stopDelayMs={200} height={3} />

      <ViewportProvider>
        <CartProvider>
          <FixedHeaderProvider>
            <AnimateSharedLayout type="crossfade">
              <Layout>
                <Component {...pageProps} />
              </Layout>
            </AnimateSharedLayout>
          </FixedHeaderProvider>
        </CartProvider>
      </ViewportProvider>
    </>
  );
}

export default MyApp;
